language: node_js
node_js: node
services:
  - redis-server
cache:
  directories:
    - node_modules
install: 
  - npm install
before_script:
  - npm run build:rest
  - sleep 10
script:
  - npm run start:rest &
  - npm test
