language: node_js
node_js: node
services:
  - mysql
cache:
  directories:
    - node_modules
install: 
  - npm install
script:
  - npm run build:rest
  - npm run start:rest
  - sleep 10
  - npm run sync:db
  - npm test
